export const ORDER_REQUESTS ="ORDER_REQUESTS";
export const ORDER_SUCCESS ="ORDER_SUCCESS";
export const ORDER_FAIL="ORDER_FAIL";


export const ORDER_DETAILS_REQUESTS ="ORDER_DETAILS_REQUESTS";
export const ORDER_DETAILS_SUCCESS ="ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL";


export const ORDER_HISTORY_REQUESTS ="ORDER_HISTORY_REQUESTS";
export const ORDER_HISTORY_SUCCESS ="ORDER_HISTORY_SUCCESS";
export const ORDER_HISTORY_FAIL="ORDER_HISTORY_FAIL";
