export const LOGIN_REQUESTS ="LOGIN_REQUESTS";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

export const LOGOUT="LOGOUT"


export const REGISTER_REQUESTS ="REGISTER_REQUESTS";
export const REGISTER_SUCCESS ="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";

export const UPDATE_REQUESTS ="UPDATE_REQUESTS";
export const UPDATE_SUCCESS ="UPDATE_SUCCESS";
export const UPDATE_FAIL="UPDATE_FAIL";