export const ALL_PRODUCT_REQUESTS ="ALL_PRODUCT_REQUESTS";
export const ALL_PRODUCT_SUCCESS ="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";


export const SLIDER_REQUESTS ="SLIDER_REQUESTS";
export const SLIDER_SUCCESS ="SLIDER_SUCCESS";
export const SLIDER_FAIL="SLIDER_FAIL";


export const CATEGORY_REQUESTS ="CATEGORY_REQUESTS";
export const CATEGORY_SUCCESS ="CATEGORY_SUCCESS";
export const CATEGORY_FAIL="CATEGORY_FAIL";

export const SINGLE_PRODUCT_REQUESTS ="SINGLE_PRODUCT_REQUESTS";
export const SINGLE_PRODUCT_SUCCESS ="SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_FAIL="SINGLE_PRODUCT_FAIL";